packages:
  - '.'

overrides:
  d3-color: 3.1.0
  next-contentlayer>next: $next
  react-simple-maps>react: $react
  react-simple-maps>react-dom: $react-dom
  react-swipeable>react: $react
  '@types/react': $@types/react
  '@types/react-dom': $@types/react-dom
